CREATE TABLE [dbo].[Item]
(
  [Id] INT NOT NULL PRIMARY KEY
, [Name] NVARCHAR(50) NOT NULL
, [Description] NVARCHAR(50) NOT NULL
, [Price] FLOAT NOT NULL
, [Quantity] INT NOT NULL
, [Image] NVARCHAR(50) NOT NULL
, [Category] NVARCHAR(50) NOT NULL
, [Picture] NVARCHAR(50) NOT NULL
)