CREATE TABLE [dbo].[Users]
(
  [Id] INT NOT NULL PRIMARY KEY
, [Name] NVARCHAR(50) NOT NULL
, [Email] NVARCHAR(50) NOT NULL
, [Password] NVARCHAR(50) NOT NULL
, [Role] NVARCHAR(50) NOT NULL
, [PhoneNumber] NVARCHAR(50) NOT NULL
, [Address] NVARCHAR(50) NOT NULL
, [cardType] NVARCHAR(50) NOT NULL
, [cardNumber] INT NOT NULL
, [cardExpiration] DATE NOT NULL
, [cardSecurityCode] NVARCHAR(50) NOT NULL
)
